[package]
name = "floneum"
version = "0.1.0"
edition = "2021"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.2.0"
futures-util = "0.3.28"
log = "0.4.17"
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["stream", "json"] }
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
anyhow = "1.0"
floneum_plugin = { path = "./plugin" }
floneumite = { path = "./floneumite" }
serde = { version = "1.0.163", features = ["derive"] }
slab = "0.4.8"
simple_logger = "4.1.0"
pollster = "0.3.0"
cargo-dist = "0.0.7"
once_cell = "1.18.0"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = [
    'component-model',
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
petgraph = { version = "0.6.4", features = ["serde-1"] }
dioxus-desktop = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus-router = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus-signals = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals", features = [
    "serialize",
] }
dioxus-free-icons = { version = "0.7.0", features = ["ionicons"] }
rfd = "0.11.4"
dioxus-std = { git = "https://github.com/DioxusLabs/dioxus-std/", version = "0.4.0", features = [
    "clipboard",
] }

[patch.crates-io]
dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus-rsx = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }

[workspace]
members = [
    "plugin",
    "rust_adapter",
    "rust_macro",
    "floneumite",
    "floneum-cli",
    "rbert",
    "floneumin",
    "floneumin-language",
    "floneumin-vision",
    "floneumin-sound",
    "plugins/generate_text",
    "plugins/generate_structured_text",
    "plugins/format",
    "plugins/search",
    "plugins/embedding",
    "plugins/embedding_db",
    "plugins/add_embedding",
    "plugins/search_engine",
    "plugins/write_to_file",
    "plugins/read_from_file",
    "plugins/if_statement",
    "plugins/contains",
    "plugins/python",
    "plugins/create_tab",
    "plugins/find_node",
    "plugins/click_node",
    "plugins/node_text",
    "plugins/type_in_node",
    "plugins/navigate_to",
    "plugins/find_child_node",
    "plugins/get_article",
    "plugins/read_rss",
    "plugins/split",
    "plugins/join",
    "plugins/slice",
    "plugins/add_to_list",
    "plugins/new_list",
    "plugins/length",
    "plugins/more_than",
    "plugins/less_than",
    "plugins/equals",
    "plugins/and",
    "plugins/or",
    "plugins/not",
    "plugins/add",
    "plugins/subtract",
    "plugins/multiply",
    "plugins/divide",
    "plugins/power",
    "plugins/number",
    "plugins/string",
]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
lto = true
# panic = "abort"
# opt-level = 3
opt-level = 'z'
# strip = true
# debug = true
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.floneum_plugin]
opt-level = 1

[features]
metal = ["floneum_plugin/metal"]
cublas = ["floneum_plugin/cublas"]
