[package]
name = "ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.2.0"
futures-util = "0.3.28"
log = "0.4.17"
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["stream"] }
serde_json = "1.0.96"
spinoff = "0.7.0"
tokio = { version = "1.28.1", features = ["full"] }
scraper = "0.16.0"
wai-bindgen-rust = "0.2.3"
egui_node_graph = { git = "https://github.com/setzer22/egui_node_graph", features = ["persistence"] }
eframe = { version = "0.21.0", features = ["persistence"] }
anyhow = "1.0"
plugin = { path = "./plugin" }
serde = { version = "1.0.163", features = ["derive"] }
slab = "0.4.8"
bincode = "1.3.3"
simple_logger = "4.1.0"

[profile.dev.package.ggml-sys]
opt-level = 3

[workspace]
members = [
    "plugin",
    "rust_adapter",
    "plugins/infer",
    "plugins/format",
    "plugins/embedding",
]
