[package]
name = "floneum-workspace"
version = "0.1.0"
edition = "2021"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[patch.crates-io]
dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus-rsx = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }

[workspace]
members = [
    "floneum",
    "plugin",
    "rust_adapter",
    "rust_macro",
    "floneumite",
    "floneum-cli",
    "rbert",
    "kalosm-llama",
    "rphi",
    "rwhisper",
    "rmistral",
    "rwuerstchen",
    "segment-anything-rs",
    "kalosm-ocr",
    "kalosm",
    "kalosm-language",
    "language-model",
    "kalosm-sample",
    "kalosm-vision",
    "kalosm-sound",
    "kalosm-streams",
    "plugins/generate_text",
    "plugins/generate_structured_text",
    "plugins/format",
    "plugins/search",
    "plugins/embedding",
    "plugins/embedding_db",
    "plugins/add_embedding",
    "plugins/search_engine",
    "plugins/write_to_file",
    "plugins/read_from_file",
    "plugins/if_statement",
    "plugins/contains",
    "plugins/python",
    "plugins/create_tab",
    "plugins/find_node",
    "plugins/click_node",
    "plugins/node_text",
    "plugins/type_in_node",
    "plugins/navigate_to",
    "plugins/find_child_node",
    "plugins/get_article",
    "plugins/read_rss",
    "plugins/split",
    "plugins/join",
    "plugins/slice",
    "plugins/add_to_list",
    "plugins/new_list",
    "plugins/length",
    "plugins/more_than",
    "plugins/less_than",
    "plugins/equals",
    "plugins/and",
    "plugins/or",
    "plugins/not",
    "plugins/add",
    "plugins/subtract",
    "plugins/multiply",
    "plugins/divide",
    "plugins/power",
    "plugins/number",
    "plugins/string",
]

[workspace.dependencies]
candle-core = { git = "https://github.com/huggingface/candle" }
candle-nn = { git = "https://github.com/huggingface/candle" }
candle-transformers = { git = "https://github.com/huggingface/candle" }
kalosm-sample = { path = "./kalosm-sample", version = "0.1.0" }
kalosm-language-model = { path = "./language-model", version = "0.1.0" }
kalosm-streams = { path = "./kalosm-streams", version = "0.1.0" }
kalosm-language = { path = "./kalosm-language", version = "0.1.0" }
kalosm-sound = { path = "./kalosm-sound", version = "0.1.0" }
kalosm-vision = { path = "./kalosm-vision", version = "0.1.0" }
kalosm = { path = "./kalosm", version = "0.1.0" }
rphi = { path = "./rphi", version = "0.1.0" }
rbert = { path = "./rbert", version = "0.1.0" }
rmistral = { path = "./rmistral", version = "0.1.0" }
kalosm-llama = { path = "./kalosm-llama", version = "0.1.0" }
rwhisper = { path = "./rwhisper", version = "0.1.0" }
rwuerstchen = { path = "./rwuerstchen", version = "0.1.0" }
segment-anything-rs = { path = "./segment-anything-rs", version = "0.1.0" }
kalosm-ocr = { path = "./kalosm-ocr", version = "0.1.0" }
llm-samplers = "=0.0.7"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
lto = true
# panic = "abort"
opt-level = 3
# opt-level = 'z'
# strip = true
debug = true
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
