[package]
name = "kalosm-streams"
version = "0.2.1"
edition = "2021"
description = "A set of streams for pretrained models in Kalosm"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]

[dependencies]
futures-util = "0.3.28"
pin-project-lite = "0.2"
tokio = { version = "1.28.1", features = ["full"] }
image = "0.24.7"
