[package]
name = "rust_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen" }
pulldown-cmark = { version = "0.9.1", default-features = false }
