[package]
name = "kalosm-parse-macro"
version = "0.2.1"
edition = "2021"
description = "A macro to derive kalosm parsing traits"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "bert", "nlp", "machine-learning", "transformers"]

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.86"
regex-automata = "0.4.5"

[lib]
proc-macro = true
