[package]
edition = "2021"
name = "kalosm"
version = "0.2.1"
authors = ["Evan Almloff"]
description = "A simple interface for pretrained AI models "
readme = "README.md"
keywords = [
    "llm",
    "llama",
    "whisper",
    "ocr",
    "nlp",
]
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"

[dependencies]
# https://github.com/floneum/floneum/issues/204
zstd-sys = { version = "=2.0.9", optional = true }

[dependencies.anyhow]
version = "1.0.75"

[dependencies.async-trait]
version = "0.1.74"

[dependencies.comfy-table]
version = "7.1.0"

[dependencies.futures-util]
version = "0.3.28"

[dependencies.hdrhistogram]
version = "7.5.4"

[dependencies.image]
version = "0.24.7"

[dependencies.kalosm-language]
version = "0.2.1"
optional = true

[dependencies.kalosm-sound]
version = "0.2.1"
optional = true

[dependencies.kalosm-streams]
version = "0.2.1"

[dependencies.kalosm-vision]
version = "0.2.1"
optional = true

[dependencies.llm-samplers]
version = "=0.0.7"

[dependencies.num-traits]
version = "0.2.17"

[dependencies.once_cell]
version = "1.19.0"

[dependencies.rand]
version = "0.8.5"

[dependencies.serde]
version = "1.0.163"
features = ["derive"]

[dependencies.surrealdb]
version = "1.1.1"
features = ["kv-rocksdb"]
optional = true

[dependencies.tokio]
version = "1.32.0"
features = [
    "full",
    "macros",
    "rt-multi-thread",
]

[dependencies.tracing]
version = "0.1.40"

[dev-dependencies.axum]
version = "0.7.2"

[dev-dependencies.candle-core]
version = "=0.3.2"

[dev-dependencies.candle-datasets]
version = "=0.3.2"

[dev-dependencies.candle-nn]
version = "=0.3.2"

[dev-dependencies.candle-transformers]
version = "=0.3.2"

[dev-dependencies.ego-tree]
version = "0.6.2"

[dev-dependencies.kalosm-llama]
version = "0.2.1"

[dev-dependencies.scraper]
version = "0.18.1"

[dev-dependencies.tokenizers]
version = "0.15.0"

[dev-dependencies.tracing-subscriber]
version = "0.2"

[features]
cublas = ["kalosm-language/cublas"]
default = [
    "language",
    "sound",
    "vision",
    "surrealdb",
]
language = ["kalosm-language"]
llamacpp = ["kalosm-language/llamacpp"]
metal = ["kalosm-language/metal"]
sound = ["kalosm-sound"]
surrealdb = ["dep:surrealdb", "dep:zstd-sys"]
vision = ["kalosm-vision"]
